# This workflow is triggered on pushes to the main branch.
# It builds and deploys the Next.js app to Firebase App Hosting.

name: Deploy to Firebase App Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/firebase-hosting-action@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUENTMIND_AI_TUTOR }}'
          projectId: fluentmind-ai-tutor
